name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # Atualiza todo dia à meia-noite
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: pedrinzz10
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_sections: most-used
          plugin_stars: yes
          plugin_followup: yes
          plugin_topics: yes
          plugin_notable: yes
